log:
  level: debug

limit:
  max_read_depth: 100

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

namespaces: 
  location: file:///home/ory/namespaces.keto.ts